/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeeklyReportsRouteImport } from './routes/_app.weekly-reports'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTeamDailyReportsRouteImport } from './routes/_app.team-daily-reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMyDashboardRouteImport } from './routes/_app.my-dashboard'
import { Route as AppMonthlyReportsRouteImport } from './routes/_app.monthly-reports'
import { Route as AppLrAnalyticsRouteImport } from './routes/_app.lr-analytics'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDailySummaryRouteImport } from './routes/_app.daily-summary'
import { Route as AppDailyReportRouteImport } from './routes/_app.daily-report'
import { Route as AppCfrAnalyticsRouteImport } from './routes/_app.cfr-analytics'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyReportsRoute = AppWeeklyReportsRouteImport.update({
  id: '/weekly-reports',
  path: '/weekly-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamDailyReportsRoute = AppTeamDailyReportsRouteImport.update({
  id: '/team-daily-reports',
  path: '/team-daily-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMyDashboardRoute = AppMyDashboardRouteImport.update({
  id: '/my-dashboard',
  path: '/my-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlyReportsRoute = AppMonthlyReportsRouteImport.update({
  id: '/monthly-reports',
  path: '/monthly-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLrAnalyticsRoute = AppLrAnalyticsRouteImport.update({
  id: '/lr-analytics',
  path: '/lr-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDailySummaryRoute = AppDailySummaryRouteImport.update({
  id: '/daily-summary',
  path: '/daily-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyReportRoute = AppDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => AppRoute,
} as any)
const AppCfrAnalyticsRoute = AppCfrAnalyticsRouteImport.update({
  id: '/cfr-analytics',
  path: '/cfr-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/cfr-analytics': typeof AppCfrAnalyticsRoute
  '/daily-report': typeof AppDailyReportRoute
  '/daily-summary': typeof AppDailySummaryRoute
  '/dashboard': typeof AppDashboardRoute
  '/lr-analytics': typeof AppLrAnalyticsRoute
  '/monthly-reports': typeof AppMonthlyReportsRoute
  '/my-dashboard': typeof AppMyDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/team-daily-reports': typeof AppTeamDailyReportsRoute
  '/users': typeof AppUsersRoute
  '/weekly-reports': typeof AppWeeklyReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/cfr-analytics': typeof AppCfrAnalyticsRoute
  '/daily-report': typeof AppDailyReportRoute
  '/daily-summary': typeof AppDailySummaryRoute
  '/dashboard': typeof AppDashboardRoute
  '/lr-analytics': typeof AppLrAnalyticsRoute
  '/monthly-reports': typeof AppMonthlyReportsRoute
  '/my-dashboard': typeof AppMyDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/team-daily-reports': typeof AppTeamDailyReportsRoute
  '/users': typeof AppUsersRoute
  '/weekly-reports': typeof AppWeeklyReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/cfr-analytics': typeof AppCfrAnalyticsRoute
  '/_app/daily-report': typeof AppDailyReportRoute
  '/_app/daily-summary': typeof AppDailySummaryRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lr-analytics': typeof AppLrAnalyticsRoute
  '/_app/monthly-reports': typeof AppMonthlyReportsRoute
  '/_app/my-dashboard': typeof AppMyDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team-daily-reports': typeof AppTeamDailyReportsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/weekly-reports': typeof AppWeeklyReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/audit-logs'
    | '/cfr-analytics'
    | '/daily-report'
    | '/daily-summary'
    | '/dashboard'
    | '/lr-analytics'
    | '/monthly-reports'
    | '/my-dashboard'
    | '/settings'
    | '/team-daily-reports'
    | '/users'
    | '/weekly-reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/audit-logs'
    | '/cfr-analytics'
    | '/daily-report'
    | '/daily-summary'
    | '/dashboard'
    | '/lr-analytics'
    | '/monthly-reports'
    | '/my-dashboard'
    | '/settings'
    | '/team-daily-reports'
    | '/users'
    | '/weekly-reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access-denied'
    | '/login'
    | '/_app/audit-logs'
    | '/_app/cfr-analytics'
    | '/_app/daily-report'
    | '/_app/daily-summary'
    | '/_app/dashboard'
    | '/_app/lr-analytics'
    | '/_app/monthly-reports'
    | '/_app/my-dashboard'
    | '/_app/settings'
    | '/_app/team-daily-reports'
    | '/_app/users'
    | '/_app/weekly-reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-reports': {
      id: '/_app/weekly-reports'
      path: '/weekly-reports'
      fullPath: '/weekly-reports'
      preLoaderRoute: typeof AppWeeklyReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team-daily-reports': {
      id: '/_app/team-daily-reports'
      path: '/team-daily-reports'
      fullPath: '/team-daily-reports'
      preLoaderRoute: typeof AppTeamDailyReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-dashboard': {
      id: '/_app/my-dashboard'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof AppMyDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monthly-reports': {
      id: '/_app/monthly-reports'
      path: '/monthly-reports'
      fullPath: '/monthly-reports'
      preLoaderRoute: typeof AppMonthlyReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lr-analytics': {
      id: '/_app/lr-analytics'
      path: '/lr-analytics'
      fullPath: '/lr-analytics'
      preLoaderRoute: typeof AppLrAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-summary': {
      id: '/_app/daily-summary'
      path: '/daily-summary'
      fullPath: '/daily-summary'
      preLoaderRoute: typeof AppDailySummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-report': {
      id: '/_app/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof AppDailyReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cfr-analytics': {
      id: '/_app/cfr-analytics'
      path: '/cfr-analytics'
      fullPath: '/cfr-analytics'
      preLoaderRoute: typeof AppCfrAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCfrAnalyticsRoute: typeof AppCfrAnalyticsRoute
  AppDailyReportRoute: typeof AppDailyReportRoute
  AppDailySummaryRoute: typeof AppDailySummaryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLrAnalyticsRoute: typeof AppLrAnalyticsRoute
  AppMonthlyReportsRoute: typeof AppMonthlyReportsRoute
  AppMyDashboardRoute: typeof AppMyDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamDailyReportsRoute: typeof AppTeamDailyReportsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWeeklyReportsRoute: typeof AppWeeklyReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCfrAnalyticsRoute: AppCfrAnalyticsRoute,
  AppDailyReportRoute: AppDailyReportRoute,
  AppDailySummaryRoute: AppDailySummaryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLrAnalyticsRoute: AppLrAnalyticsRoute,
  AppMonthlyReportsRoute: AppMonthlyReportsRoute,
  AppMyDashboardRoute: AppMyDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamDailyReportsRoute: AppTeamDailyReportsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWeeklyReportsRoute: AppWeeklyReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
